# Generated by Django 6.0.2 on 2026-04-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('plan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('plan_name', models.CharField(max_length=100, unique=True)),
                ('plan_description', models.TextField()),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('priority_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('formatted_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Free_Time',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productivity_site.user')),
                ('monday', models.IntegerField(default=0)),
                ('tuesday', models.IntegerField(default=0)),
                ('wednesday', models.IntegerField(default=0)),
                ('thursday', models.IntegerField(default=0)),
                ('friday', models.IntegerField(default=0)),
                ('saturday', models.IntegerField(default=0)),
                ('sunday', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.user')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('autobilling', models.BooleanField(default=False)),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.plan')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.user')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('podcast_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('summary_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.summary')),
            ],
        ),
        migrations.CreateModel(
            name='Multioption',
            fields=[
                ('multioption_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('valid_answers', models.CharField(max_length=255)),
                ('hint', models.CharField(max_length=255)),
                ('answer1', models.CharField(max_length=255)),
                ('answer2', models.CharField(max_length=255)),
                ('answer3', models.CharField(max_length=255)),
                ('answer4', models.CharField(max_length=255)),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('summary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.summary')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('flashcard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('valid_answers', models.CharField(max_length=255)),
                ('hint', models.CharField(max_length=255)),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('summary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.summary')),
            ],
        ),
        migrations.CreateModel(
            name='Fill_Blanks',
            fields=[
                ('fill_blanks_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('valid_answers', models.CharField(max_length=255)),
                ('hint', models.CharField(max_length=255)),
                ('times_answered', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('summary_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.summary')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('syllabus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(default=0)),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.subject')),
            ],
        ),
        migrations.AddField(
            model_name='summary',
            name='syllabus_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.syllabus'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('estimated_time', models.IntegerField()),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productivity_site.priority')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('subtask_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('estimated_time', models.IntegerField()),
                ('priority_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='productivity_site.priority')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productivity_site.task')),
            ],
        ),
    ]
