# Generated by Django 6.0.2 on 2026-04-15 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_site', '0002_alter_free_time_user_id_alter_subscription_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='plan_id',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
    ]
