# Generated by Django 6.0.2 on 2026-04-15 15:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_site', '0003_remove_subscription_plan_id_delete_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fill_Blanks',
            new_name='FillBlanks',
        ),
        migrations.RenameModel(
            old_name='Free_Time',
            new_name='FreeTime',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
