# Generated by Django 6.0.2 on 2026-05-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_site', '0007_task_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='priority_id',
        ),
        migrations.AddField(
            model_name='subtask',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
