# Generated by Django 6.0.2 on 2026-05-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_site', '0008_remove_subtask_priority_id_subtask_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
