# Generated by Django 6.0.2 on 2026-06-05 12:04

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity_site', '0009_subtask_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='color',
            field=models.CharField(default='#f59e0b', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a valid hex color.', regex='^#[0-9a-fA-F]{6}$')]),
        ),
        migrations.AlterField(
            model_name='subtask',
            name='estimated_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('user_id', 'name'), name='unique_subject_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='subtask',
            constraint=models.UniqueConstraint(fields=('task_id', 'name'), name='unique_subtask_name_per_task'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('subject_id', 'name'), name='unique_task_name_per_subject'),
        ),
    ]
